name: CI for Dockerbuild

on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker build
        runs: |
          docker build -t my-redis -f Dockerfile.redis .
          docker build -t my-mysql -f Dockerfile.mysql .
          docker build -t my-mongo -f Dockerfile.mongo .

      - name: Set up Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin
      
      - name: Kustomize build
        run: kustomize build .